name: "CI"
on: [push, pull_request]

permissions:
    contents: read
jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node: [ 20, 22, 24 ]

        name: Test(Node ${{ matrix.node }} on ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
              with:
                persist-credentials: false

            - name: Install pnpm
              uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: ${{ matrix.node }}
                  cache: "pnpm"
            - name: Install
              run: pnpm install
            - name: Test
              run: pnpm test
            - name: Test Examples
              run: pnpm run test:examples

    benchmark:
        name: Benchmark
        runs-on: ubuntu-latest
        permissions:
            contents: write
        if: github.event_name == 'push'
        steps:
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
              with:
                persist-credentials: false

            - name: Install pnpm
              uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: 22
                  cache: "pnpm"
            - name: Install Hyperfine
              run: |
                  wget https://github.com/sharkdp/hyperfine/releases/download/v1.15.0/hyperfine_1.15.0_amd64.deb
                  sudo dpkg -i hyperfine_1.15.0_amd64.deb
            - name: Install
              run: pnpm install
            - name: Build textlint
              run: pnpm run build
            - name: Benchmark
              run: pnpm run bench
              working-directory: ./test/benchmark
            - name: Get Previous Benchmark Results
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                  path: ./cache
                  key: ${{ runner.os }}-benchmark
            - name: Save Benchmark Results
              uses: benchmark-action/github-action-benchmark@4bdcce38c94cec68da58d012ac24b7b1155efe8b # v1.20.7
              with:
                  tool: "customSmallerIsBetter"
                  output-file-path: ./test/benchmark/output.json
                  benchmark-data-dir-path: "benchmarks"
                  fail-on-alert: true
                  comment-on-alert: true
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  auto-push: true
            - name: Output Step Summary
              run: |
                  cat ./test/benchmark/result.md > $GITHUB_STEP_SUMMARY
                  echo "- <https://textlint.org/textlint/benchmarks/>" >> $GITHUB_STEP_SUMMARY
    e2e:
        name: E2E
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
              with:
                submodules: recursive
                persist-credentials: false

            - name: Install pnpm
              uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: 22
                  cache: "pnpm"
            - name: Install
              run: pnpm install
            - name: Build textlint
              run: pnpm run build
            - name: Integration Tests
              run: pnpm run test:integration

    documentation:
        strategy:
            matrix:
                node: [22]

        name: Documentation(Node ${{ matrix.node }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
              with:
                submodules: recursive
                persist-credentials: false

            - name: Install pnpm
              uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: ${{ matrix.node }}
                  cache: "pnpm"
            - name: Install
              run: pnpm install
            - run: pnpm run test:docs
            - run: pnpm run website
