name: WebSite Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'docs/**'
      - 'website/**'
      - '.github/workflows/website-preview.yml'

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        if: github.event.action != 'closed'
        
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        if: github.event.action != 'closed'
        with:
          node-version: 22
          cache: "pnpm"
          
      - name: Install dependencies
        if: github.event.action != 'closed'
        run: pnpm install

      - name: Build website
        if: github.event.action != 'closed'
        run: |
          pnpm run website
        env:
          DOCUSAURUS_BASE_URL: "/textlint/pr-preview/pr-${{ github.event.number }}/"

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@9f77b1d057b494e662c50b8ca40ecc63f21e0887 # v1.6.2
        with:
          source-dir: ./website/build
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
          deploy-repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
